swagger: '2.0'
info:
  description: Cloud API which serves for schedulling apps
  title: Cloud Admin API
  contact:
    name: Alexandru-Mihai Cioplean, Alexandru Udristioiu
    email: alexandru.cioplean@gmail.com, udristioiualexandru@gmail.com
  license:
    name: MIT
    url: http://mit.org
  version: 1.6.0
paths:
  /app:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - apps
      summary: Retrieves apps information by name
      operationId: GetAppsInfo
      parameters:
        - type: string
          description: user unique id
          name: USER-UUID
          in: header
          required: true
        - type: string
          description: role used for auth
          name: USER-AUTH
          in: header
          required: true
        - type: array
          items:
            type: string
          collectionFormat: csv
          description: name of the apps
          name: appnames
          in: query
          allowEmptyValue: true
        - type: string
          description: owner of the app
          name: username
          in: query
          required: true
        - type: string
          description: filter apps by name(keyword), description(keyword), is_running, created/updated timestamp combined(AND-u0026u0026,OR-||) or separate
          name: filter
          in: query
          allowEmptyValue: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/domain.GetApplicationsData'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.GetApplicationsData'
        '404':
          description: App Not Found
          schema:
            $ref: '#/definitions/domain.GetApplicationsData'
    put:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - apps
      summary: Update app information
      operationId: UpdateApp
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/domain.ApplicationData'
        - type: string
          description: role used for auth
          name: USER-AUTH
          in: header
          required: true
        - type: string
          description: user unique id
          name: USER-UUID
          in: header
          required: true
        - type: string
          description: owner of the app
          name: username
          in: query
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: string
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
    delete:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - apps
      summary: Deletes app
      operationId: DeleteApp
      parameters:
        - type: string
          description: role used for auth
          name: USER-AUTH
          in: header
          required: true
        - type: string
          description: user unique id
          name: USER-UUID
          in: header
          required: true
        - type: array
          items:
            type: string
          collectionFormat: csv
          description: name of the apps you want to delete
          name: appname
          in: query
          required: true
        - type: string
          description: owner of the app
          name: username
          in: query
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: string
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        '403':
          description: User not allowed as admin
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        '404':
          description: User Not Found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
  /login:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - users
      summary: Login user
      operationId: UserLogin
      parameters:
        - type: boolean
          description: old pass for changing password
          name: old_password
          in: query
          allowEmptyValue: true
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/domain.UserData'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/domain.UserData'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        '404':
          description: User Not Found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
  /register/app:
    post:
      consumes:
        - multipart/form-data
      produces:
        - application/json
      tags:
        - apps
      summary: Upload app to s3
      operationId: UploadApp
      parameters:
        - type: string
          description: role used for auth
          name: USER-AUTH
          in: header
          required: true
        - type: string
          description: user unique id
          name: USER-UUID
          in: header
          required: true
        - type: string
          description: owner of the app
          name: username
          in: query
          required: true
        - type: array
          items:
            type: string
          description: zip archive which contains the code and description files(same name for both,description being txt,order for every app is source_code,then description)
          name: type
          in: formData
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: string
        '302':
          description: Already found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
  /register/user:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - users
      summary: Register user
      operationId: UserRegister
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/domain.UserData'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '302':
          description: Already found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
  /user:
    put:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - users
      summary: Updates user profile
      operationId: UpdateUserProfile
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/domain.UserData'
        - type: string
          description: role used for auth
          name: USER-AUTH
          in: header
          required: true
        - type: string
          description: user unique id
          name: USER-UUID
          in: header
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: string
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
    delete:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - users
      summary: Deletes user
      operationId: DeleteUser
      parameters:
        - type: string
          description: role used for auth
          name: USER-AUTH
          in: header
          required: true
        - type: string
          description: user unique id
          name: USER-UUID
          in: header
          required: true
        - type: array
          items:
            type: string
          collectionFormat: csv
          description: username of the account
          name: username
          in: query
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: string
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        '404':
          description: User Not Found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
  /user/{username}:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - users
      summary: Retrieves user profile
      operationId: GetUserProfile
      parameters:
        - type: string
          description: username of the account
          name: username
          in: path
          required: true
        - type: string
          description: role used for auth
          name: USER-AUTH
          in: header
          required: true
        - type: string
          description: user unique id
          name: USER-UUID
          in: header
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/domain.UserData'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        '404':
          description: User Not Found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
definitions:
  domain.ApplicationData:
    required:
      - created_timestamp
      - updated_timestamp
      - name
      - description
      - is_running
    properties:
      created_timestamp:
        type: string
        format: date-time
      description:
        type: string
      is_running:
        type: string
      name:
        type: string
      updated_timestamp:
        type: string
        format: date-time
  domain.ErrorResponse:
    required:
      - message
      - status_code
    properties:
      message:
        type: string
      status_code:
        type: integer
        format: int32
  domain.GetApplicationsData:
    required:
      - Response
      - Errors
    properties:
      Errors:
        type: array
        items:
          $ref: '#/definitions/domain.ErrorResponse'
      Response:
        type: array
        items:
          $ref: '#/definitions/domain.ApplicationData'
  domain.UserData:
    required:
      - username
      - nr_deployed_apps
    properties:
      applications:
        type: array
        items:
          type: string
      birth_date:
        type: string
      email:
        type: string
      full_name:
        type: string
      job_role:
        type: string
      joined_date:
        type: string
        format: date-time
      last_time_online:
        type: string
        format: date-time
      nr_deployed_apps:
        type: integer
        format: int32
      password:
        type: string
      role:
        type: string
      user_id:
        type: string
      username:
        type: string
      want_notify:
        type: string
tags:
  - description: Managing users
    name: users
  - description: Managing apps
    name: apps
